apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "mariadb.mariadb.com/v1alpha1",
          "kind": "MariaDB",
          "metadata": {
            "name": "example-mariadb",
            "namespace": "example-mariadb"
          },
          "spec": {
            "mariadb_image": "mariadb:10.4",
            "mariadb_password": "CHANGEME",
            "mariadb_pvc_storage_request": "1Gi",
            "masters": 1,
            "replicas": 0
          }
        }
      ]
    capabilities: Basic Install
  name: mariadb-operator.v1.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: MariaDB
      name: mariadbs.mariadb.mariadb.com
      version: v1alpha1
  description: Placeholder description
  displayName: Mariadb Operator
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - services/finalizers
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - apps
          - extensions
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - apps
          resourceNames:
          - mariadb-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - get
        - apiGroups:
          - apps
          resources:
          - replicasets
          verbs:
          - get
        - apiGroups:
          - mariadb.mariadb.com
          resources:
          - '*'
          verbs:
          - '*'
        serviceAccountName: mariadb-operator
      deployments:
      - name: mariadb-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: mariadb-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: mariadb-operator
            spec:
              containers:
              - command:
                - /usr/local/bin/ao-logs
                - /tmp/ansible-operator/runner
                - stdout
                image: '{{ operator_image }}'
                imagePullPolicy: '{{ pull_policy|default(''Always'') }}'
                name: ansible
                resources: {}
                volumeMounts:
                - mountPath: /tmp/ansible-operator/runner
                  name: runner
                  readOnly: true
              - env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: mariadb-operator
                image: '{{ operator_image }}'
                imagePullPolicy: '{{ pull_policy|default(''Always'') }}'
                name: operator
                resources: {}
                volumeMounts:
                - mountPath: /tmp/ansible-operator/runner
                  name: runner
              serviceAccountName: mariadb-operator
              volumes:
              - emptyDir: {}
                name: runner
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  maturity: alpha
  provider: {}
  replaces: mariadb-operator.v0.0.0
  version: 1.0.0
